### PR TITLE
Simplify the l10n string for free install text (bug 1180839)

### PR DESCRIPTION
**Pull request by mstriemer**
https://bugzilla.mozilla.org/show_bug.cgi?id=1180839

### CODE REVIEW

**Comment by sherlockedci** [comment]
[ The Adventure of the Speckled Build](http://sherlocked.dev.mozaws.net/builds/70984779)

**Comment by sherlockedci** [comment]
[ The Adventure of the Sussex Build](http://sherlocked.dev.mozaws.net/builds/71082514)

**Comment by sherlockedci** [comment]
[ The Adventure of the Golden Build](http://sherlocked.dev.mozaws.net/builds/71084123)

**Comment by sherlockedci** [comment]
[ The Adventure of the Solitary Build](http://sherlocked.dev.mozaws.net/builds/71084612)

**Comment by sherlockedci** [comment]
[ The Adventure of the Devil's Build](http://sherlocked.dev.mozaws.net/builds/71086079)

**Comment by sherlockedci** [comment]
[ The Adventure of the Mazarin Build](http://sherlocked.dev.mozaws.net/builds/71087445)

**Comment by sherlockedci** [comment]
[ The Adventure of the Norwood Build](http://sherlocked.dev.mozaws.net/builds/71087367)

**Comment by sherlockedci** [comment]
[ The Adventure of the Creeping Build](http://sherlocked.dev.mozaws.net/builds/71087837)

**Comment by mstriemer** [comment]
Comments welcome.

**Pull request merged**
