### PR TITLE
add pagination to game listing page

### PR DESCRIPTION
**Pull request by ngokevin**
screen shot 2015-08-18 at 11 08 22 am

### CODE REVIEW

**Comment by chuckharmston** [comment]
Didn't you do something specific to prevent pagination on the endpoint?

**Comment by ngokevin** [comment]
I prevented compat filtering and content type filtering, not pagination. This only applies for the listing page which uses the search endpoint.

**Comment by chuckharmston** [comment]
Ah, right, you just did that via paginator.

**Comment by chuckharmston** [comment]
screen shot 2015-08-18 at 4 25 03 pm
The button shows up when there's nothing that needs paginating.

**Comment by chuckharmston** [comment]
I get a noop when I actually click the button.

**Comment by chuckharmston** [comment]
Looks good otherwise though, r+wc

**Comment by chuckharmston** [comment]
r+

**Comment by ngokevin** [comment]
thanks!

**Pull request merged**
