### PR TITLE
Align search on mobile (bug 1157356)

### PR DESCRIPTION
**Pull request by mstriemer**
align-search-bar-again mov

### CODE REVIEW

**Comment by mstriemer** [comment]
r? @ngokevin 

This fixes the issue on mobile but I left the input centred as it was before at desktop widths.

**Comment by chuckharmston** [comment]
Not a designer, but can we align the search icon with the burger? It looks sloppy.

screen shot 2015-04-22 at 2 45 55 pm

**Comment by mstriemer** [comment]
Good call

**Comment by ngokevin** [comment]
What issue does this fix on mobile? I thought we were centering it.

Also I feel the purpose of having a placeholder is defeated if it's hidden on focus.

**Comment by mstriemer** [comment]
The input wasn't aligned correctly at around 400px. You can see it in your screenshot from the bug.

screen shot 2015-04-22 at 10 46 11 am

**Comment by mstriemer** [comment]
This doesn't change how the placeholder was working, it's hiding when the form is valid.

**Comment by ngokevin** [comment]
Didn't see that when I saw the bug, my issue was more that it wasn't centered

**Comment by ngokevin** [comment]
When I click the search toggle, all I see is the cursor. So the placeholder is not visible.

**Comment by mstriemer** [comment]
On this branch on the one I linked to in chat? That's what would happen on the other branch but it should be the same on this one.

**Comment by ngokevin** [comment]
Ah, okay.

**Comment by ngokevin** [comment]
r+, i'm fine with it left-aligned on mobile (krupa was too)

are we going to keep trying to center it on desktop

**Comment by mstriemer** [comment]
I'm fine with centring it on mobile and desktop but then we need to revisit the placeholder. If we want to truly centre the text then the placeholder and the input won't line up.

**Comment by mstriemer** [comment]
Although I don't hate it left aligned everywhere.
screenshot 2015-04-22 16 11 12

**Comment by ngokevin** [comment]
I don't think I mind that either. Given we align it with the rocket ofc

**Comment by mstriemer** [comment]
Less rocket padding

screenshot 2015-04-22 16 13 37

@pwalm what do you think? Should we always left align the search bar?

**Comment by ngokevin** [comment]
The rocket padding is part of the spec (40px) so it's better to move the input to the right

**Comment by pwalm** [comment]
I would prefer we follow the original design and keep search centered.

**Comment by pwalm** [comment]
Sorry, to clarify: search icon + copy should be centered to the page as a group.

**Comment by ngokevin** [comment]
Okay. We're only gravitating towards this since it's technically difficult to center

**Comment by chuckharmston** [comment]
Or more specifically, we aren't easily able to treat the icon as a character of text that we should center.

**Comment by ngokevin** [comment]
The icon is not too bad since we could just offset it based on the width of the icon. I think it's difficult since we're forced to manually create the input placeholder since some browsers hide it on focus.

**Comment by pwalm** [comment]
tim-gunn-slower

**Comment by chuckharmston** [comment]
img_6786

**Comment by pwalm** [comment]
Mark and I just had a chat: we're removing the icon from the search field because it's not necessary, and he's going to work on centering the "Search Marketplace..." copy and what happens to it once the user starts typing. We'll slay this dragon yet, gentlemen.

**Comment by mstriemer** [comment]
Initial mock of what will happen, I'm going to merge this mobile fix for now.

centre-search-when-valid-mock mov

**Pull request merged**
