### PR TITLE
refresh header login buttons (bug 1129350)

### PR DESCRIPTION
**Pull request by ngokevin**
screen shot 2015-02-04 at 6 39 06 pm

### CODE REVIEW

**Comment by spasovski** [comment]
I see this



and



while logged in.

**Comment by ngokevin** [comment]
thanks forgot to check that case, updated

**Comment by ngokevin** [comment]
screen shot 2015-02-04 at 6 58 30 pm

**Comment by spasovski** [comment]
Looks good thanks r+

**Comment by ngokevin** [comment]
yay

**Pull request merged**
