### PR TITLE
Bug 1184864 - [Android] Horizontal scroll

### PR DESCRIPTION
**Pull request by tsl143**

### CODE REVIEW

**Comment by tsl143** [comment]
screenshot_2015-08-11-22-55-11
screenshot_2015-08-11-23-09-46

**Comment by tsl143** [comment]
@mstriemer r?

**Comment by tsl143** [comment]
@spasovski r?

**Comment by mstriemer** [comment]
This regresses the feed for me. It fixes the scroll on the detail page but there is now 10px of padding around the header background on the feed.

screenshot_2015-08-20-08-46-47

**Comment by tsl143** [comment]
reverted `brands.styl`, instead added `overflow: hidden` to `feed-landing-header`

**Comment by ngokevin** [comment]
Maybe make this apply to mobile only. This regresses:

**Comment by tsl143** [comment]
@ngokevin r?

**Comment by ngokevin** [comment]
can you address

> Maybe make this apply to mobile only. This regresses:

**Comment by ngokevin** [comment]
reopen when it's updated thanks!

**Pull request closed without merging**
