### PR TITLE
nuke app list borders for colored lists (bug 1126571)

### PR DESCRIPTION
**Pull request by spasovski**

### CODE REVIEW

**Comment by ngokevin** [comment]
I had this before. I think @pwalm wanted borders.

**Comment by spasovski** [comment]
We'd need a JS solution to that which also waits on `window.resize`. Unless @pwalm you're alright with the way it is without this patch at https://marketplace-dev.allizom.org/feed/collection/kj?src=collection-element

**Comment by pwalm** [comment]
@pwalm wants borders! :D

**Comment by spasovski** [comment]
The tribe has spoken.

**Pull request closed without merging**
