### PR TITLE
Bug 1162913 - Footer Newsletter bar is not align correctly

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
Footer Newsletter bar is now align correctly

### CODE REVIEW

**Comment by atiqueahmedziad** [comment]
@ddurst  @diox  please review this ....last time conflicted :( ...sorry for that

**Comment by ngokevin** [comment]
It looks a bit skewed since we're centering a left-aligned block. Maybe we should just center the whole thing? We can do that with flexbox's justify-content. 

screen shot 2015-05-13 at 2 23 51 pm

**Comment by atiqueahmedziad** [comment]
Even after using ``justify-content: center`` `display: flex` `flex-wrap: wrap` . Its also needs margin & padding 
capture

**Comment by ngokevin** [comment]
That doesn't look bad to me. Is that screenshot with additional margin/padding needed to center it?

**Comment by atiqueahmedziad** [comment]
Nope .. That didn't take any margin & padding . But we can do the same with putting  `text-align: center;` in  class `.newsletter` without doing `justify-content: center;` `display: flex;` `flex-wrap: wrap;`. 
So, will I use  `text-align: center;` in  class `.newsletter` ? It gives same result

**Comment by atiqueahmedziad** [comment]
updated the commit . It looks like- 
capture

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by atiqueahmedziad** [comment]
@ngokevin  pls check it :)

**Comment by ngokevin** [comment]
@pwalm this look okay to you?

**Comment by pwalm** [comment]
@ngokevin Looks good! :+1:

**Comment by ngokevin** [comment]
Thanks atique

**Pull request merged**
