### PR TITLE
Set app install state before updating text (bug 1183072)

### PR DESCRIPTION
**Pull request by mstriemer**
https://bugzilla.mozilla.org/show_bug.cgi?id=1183072

### CODE REVIEW

**Comment by chuckharmston** [comment]
r+ with a test

**Comment by mstriemer** [comment]
This is really hard to test, hence why I didn't test it before.

**Comment by chuckharmston** [comment]
There's presumably a side effect of this not being in place that would be testable, right?

**Comment by mstriemer** [comment]
Leaving the test out because this code is too deeply nested.

**Comment by sherlockedci** [comment]
[ The Adventure of the Abbey Build](http://sherlocked.dev.mozaws.net/builds/71961865)

**Pull request merged**
