### PR TITLE
Hide content filtering on "desktop"

### PR DESCRIPTION
**Pull request by mstriemer**
https://bugzilla.mozilla.org/show_bug.cgi?id=1173023

### CODE REVIEW

**Comment by sherlockedci** [comment]
[ The Adventure of the Speckled Build](http://sherlocked.dev.mozaws.net/builds/66607562)

**Comment by sherlockedci** [comment]
[ The Adventure of the Noble Build](http://sherlocked.dev.mozaws.net/builds/67396857)

**Comment by mstriemer** [comment]
This depends on https://github.com/mozilla/marketplace-core-modules/pull/44.

**Comment by sherlockedci** [comment]
[ The Adventure of the Blanched Build](http://sherlocked.dev.mozaws.net/builds/67399594)

**Comment by ngokevin** [comment]
relevant unit test failures

r+ once fixed

**Comment by mstriemer** [comment]
Need the updates from https://github.com/mozilla/marketplace-core-modules/pull/44 for them to pass.

**Comment by ngokevin** [comment]
aite just pull em in here

**Comment by mstriemer** [comment]
Totally lied to you, they're mocked.

**Comment by sherlockedci** [comment]
[ The Adventure of the Mazarin Build](http://sherlocked.dev.mozaws.net/builds/67574480)

**Comment by sherlockedci** [comment]
[ The Adventure of the Blue Build](http://sherlocked.dev.mozaws.net/builds/67574600)

**Comment by sherlockedci** [comment]
[ The Adventure of the Musgrave Build](http://sherlocked.dev.mozaws.net/builds/67888587)

**Comment by sherlockedci** [comment]
[ The Adventure of the Five Orange Build](http://sherlocked.dev.mozaws.net/builds/67889586)

**Comment by sherlockedci** [comment]
[ The Adventure of the Red Build](http://sherlocked.dev.mozaws.net/builds/67889789)

**Pull request merged**
