### PR TITLE
stop navbar-linefitting event listeners from getting called again on every page load (bug 1109448; bug 1059002)

### PR DESCRIPTION
**Pull request by cvan**
https://bugzilla.mozilla.org/show_bug.cgi?id=1109448
https://bugzilla.mozilla.org/show_bug.cgi?id=1059002

### CODE REVIEW

**Comment by andymckay** [comment]
any update here?

**Comment by cvan** [comment]
> any update here?

@ngokevin r?

**Comment by ngokevin** [comment]
the navbar smooth scroll patch was pulled + pwalm is in progress with the new navbar as we saw in portland. might want to close this

**Comment by cvan** [comment]
okay. should make sure that the event listeners get fixed because there are a lot of events getting fired atm.

**Pull request closed without merging**
