### PR TITLE
Fix header title for homepage

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
The PR #1590 seems very old & does have conflicts. So, I have created this new pr. 
Please have a check @ddurst 
### After applying this patch
screen shot 2016-04-16 at 05 58 20

### CODE REVIEW

**Comment by ddurst** [comment]
Assuming the width issue is the same as in the previous PR (and remains at 215), I'm fine with this.

**Comment by atiqueahmedziad** [comment]
@ddurst Yes, haven't changed width. So, it remains at 215px.

**Comment by ddurst** [comment]
This wfm. @spasovski -- 2 for 1 r? ;)

**Comment by spasovski** [comment]
Looks good r+ thanks!

**Pull request merged**
