### PR TITLE
add spoke-header page type (bug 1218945)(1515)

### PR DESCRIPTION
**Pull request by spasovski**

### CODE REVIEW

**Comment by chuckharmston** [comment]
I don't think the search icon should be appearing on these pages.

**Comment by chuckharmston** [comment]
r+wc

**Comment by ngokevin** [comment]
what's the plan with spoke/header? it's a bit inconsistent. it's not on a lot of pages. website/apps detail pages show "X Detail" but addons show "Addon Name"

**Comment by spasovski** [comment]
It felt out of scope for the core bug but more header titles will become spoke/header as part of the UI debt work coming after 2.5. I'd prefer to keep this PR small so that it has less chances of regressions.

**Pull request merged**
