### PR TITLE
Bug 1135145 - Search field should be larger at tablet width so text is not truncated

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
Now text in the search box will not truncated.

### CODE REVIEW

**Comment by andymckay** [comment]
screenshot 2015-03-23 09 22 59

Looks pretty good to me.

**Comment by andymckay** [comment]
Travis failure looks unrelated.

**Comment by andymckay** [comment]
Curious how you've got 3 commits on the pull request though, can we rebase that down to one please? Other than that looks good, thank you!

**Comment by atiqueahmedziad** [comment]
@andymckay yeah, its okey now :) ... sorry i dn't know how did that happend.

**Pull request merged**
