### PR TITLE
Flip desktop promo arrow navigation in RTL (bug 1169765)

### PR DESCRIPTION
**Pull request by mstriemer**

### CODE REVIEW

**Comment by ngokevin** [comment]
we should start PRing to master to kick the visual regressions

**Comment by mstriemer** [comment]
Will reopen.

**Comment by chuckharmston** [comment]
What do you mean?

screen shot 2015-05-29 at 4 52 34 pm

**Comment by ngokevin** [comment]
Sorry, not master. The origin/mozilla repo. ```mozilla:master from mstriemer:rtl``` vs ```mozilla:master from mozilla:rtl```

**Comment by chuckharmston** [comment]
:+1:

**Pull request closed without merging**
