### PR TITLE
Centre the newsletter form as a block (bug 1169215)

### PR DESCRIPTION
**Pull request by mstriemer**
screenshot 2015-05-29 22 10 29
screenshot 2015-05-29 22 10 44

### CODE REVIEW

**Comment by sherlockedci** [comment]
[ The Adventure of the Sussex Build](http://sherlocked.dev.mozaws.net/builds/64667132)

**Comment by sherlockedci** [comment]
[ The Adventure of the Wisteria Build](http://sherlocked.dev.mozaws.net/builds/64993829)

**Comment by sherlockedci** [comment]
[ The Adventure of the Twisted Build](http://sherlocked.dev.mozaws.net/builds/65019602)

**Comment by sherlockedci** [comment]
[ The Adventure of the Blue Build](http://sherlocked.dev.mozaws.net/builds/65089705)

**Comment by ngokevin** [comment]
r+

**Pull request merged**
