### PR TITLE
Fix redundancy issue in Report Abuse page on mobile (bug 1179799)

### PR DESCRIPTION
**Pull request by atiqueahmedziad**

### CODE REVIEW

**Comment by spasovski** [comment]
As the previous comment - we'd lose the only title on desktop.

**Comment by atiqueahmedziad** [comment]
Done :) 
check pls

**Comment by mstriemer** [comment]
Might be worth doing this change in #1363. Looks like this depends on the CSS changes in there?

**Comment by atiqueahmedziad** [comment]
Closing it since #1363 deals with the css :)

**Pull request closed without merging**
