### PR TITLE
[WIP] RTL preview missing indicator

### PR DESCRIPTION
**Pull request by mstriemer**
https://bugzilla.mozilla.org/show_bug.cgi?id=1169231

### CODE REVIEW

**Comment by sherlockedci** [comment]
[ The Adventure of the Priory Build](http://sherlocked.dev.mozaws.net/builds/65179567)

**Comment by sherlockedci** [comment]
[ The Adventure of the Silver Build](http://sherlocked.dev.mozaws.net/builds/65180230)

**Comment by sherlockedci** [comment]
[ The Adventure of the Musgrave Build](http://sherlocked.dev.mozaws.net/builds/65184257)

**Comment by mstriemer** [comment]
Looks like the original screenshot didn't get grabbed (it was in English in the second build and in the third there is only Arabic and one of the screenshots has a URL of `null`).

But the screenshots now have the indicators.

**Comment by mstriemer** [comment]
The next sherlocked build won't have RTL since I removed the mcm changes in https://github.com/mozilla/marketplace-core-modules/pull/43 from the bower.json.

**Comment by sherlockedci** [comment]
[ The Adventure of the Illustrious Build](http://sherlocked.dev.mozaws.net/builds/65185689)

**Comment by sherlockedci** [comment]
[ The Adventure of the Naval Build](http://sherlocked.dev.mozaws.net/builds/65251400)

**Comment by spasovski** [comment]
r+

**Pull request merged**
