### PR TITLE
BUG : 1174351 report issue button to link

### PR DESCRIPTION
**Pull request by shiveeg1**
BUG : 1174351 button set to link and font weight set to 500

### CODE REVIEW

**Comment by spasovski** [comment]
Is there a bug associated with this?

**Comment by atiqueahmedziad** [comment]
Bug 1174351 
@shiveeg1 can you please edit the commit title & pr title with bug number if possible?

**Comment by atiqueahmedziad** [comment]
Change the commit title pls

**Comment by mstriemer** [comment]
Looks good, as atique mentioned in the future can you please format your commit messages like: `Use link instead of button for report issue (bug 1174351)`

**Comment by mstriemer** [comment]
Thanks for the patch!

**Comment by shiveeg1** [comment]
Always a pleasure. Look forward to more. :)

**Pull request merged**
