### PR TITLE
no search results cleanup (bug 1127515)

### PR DESCRIPTION
**Pull request by spasovski**
Also fixes a minor dependency issue.

### CODE REVIEW

**Comment by ngokevin** [comment]
Shouldn't we hide the display toggle?

That typography also looks a bit outdated. I think the font we are using for subheaders would fit better (could also get rid of the "No Results" CSS maybe too

**Comment by ngokevin** [comment]
Adding a check for the dropdown on the tests/ui/search.js's no result tests would be nice

**Comment by ngokevin** [comment]
r+wc

**Comment by spasovski** [comment]
I actually really agree with hiding the toggle but not confident enough in my fight against Krupa. We didn't have a mock for this but the fat font does look weird now.

**Comment by ngokevin** [comment]
She'll agree, there's no reason to have it.

**Pull request merged**
