### PR TITLE
Add safe option to .name for the desktop header.

### PR DESCRIPTION
**Pull request by ddurst**
This should eliminate the presentation of HTML-encoded strings in the page header.

### CODE REVIEW

**Comment by mstriemer** [comment]
What does this fix?

**Comment by spasovski** [comment]
No bug number in commit comment...
#r-

**Comment by ddurst** [comment]
This fixes the errant HTML entities in feed item pages. But perhaps it's a non-issue and we have bad data. I'll have Scott check the data.

**Comment by ddurst** [comment]
Non-issue. Just overlooked data after https://github.com/mozilla/zamboni/pull/3107 and https://github.com/mozilla/fireplace/pull/1254 were merged.

**Comment by ddurst** [comment]
Also: sigh.

**Pull request closed without merging**
