### PR TITLE
Fix active/inactive states in category page toggles (bug 1123897).

### PR DESCRIPTION
**Pull request by chuckharmston**
After talking it over with @pwalm, he agreed with me that having the bright color be inactive and the underline indicate the active was a little bit awkward, as both could be used to indicate the active state. He asked me to remove the underline, and the active state be black and have the default cursor with no underline, while inactive be blue and underline on hover. This was hit in 35aac0b.

Additionally, we noticed that there was then an inconsistency between active/inactive colors between this toggle and the preview tray toggle. He indicated that the preview tray toggle was wrong, and asked me to switch it. That was in 6979b33.

r? @ngoke @spasovski 

# Before

screen shot 2015-02-18 at 3 31 47 pm

# After

screen shot 2015-02-18 at 3 31 00 pm

### CODE REVIEW

**Comment by spasovski** [comment]
I'd squash this but r+ otherwise. Thanks for the help.

**Comment by chuckharmston** [comment]
Not going to squash because one commit is unrelated to the bug, but thanks for the review!

**Comment by spasovski** [comment]
pedant!

**Comment by chuckharmston** [comment]
PEDANT

**Pull request merged**
