### PR TITLE
Use a different marketplace-gulp version

### PR DESCRIPTION
**Pull request by mstriemer**
Testing some slimer stuff.

### CODE REVIEW

**Comment by sherlockedci** [comment]
[ The Adventure of the Illustrious Build](http://sherlocked.dev.mozaws.net/builds/81495027)

**Comment by sherlockedci** [comment]
[ The Adventure of the Lion's Build](http://sherlocked.dev.mozaws.net/builds/81495107)

**Comment by davehunt** [comment]
@mstriemer I see your latest patch here installs latest ESR and then downloads a specific version for use by SlimerJS. Are you okay with this approach? If so, I'll just pull this change into #1486.

**Comment by mstriemer** [comment]
@davehunt I added some caching and cleaned it up a bit. I'll merge this in and you can rebase and check that your branch is working with it.

**Pull request merged**
