### PR TITLE
Load settings first thing in main (bug 1138690)

### PR DESCRIPTION
**Pull request by mstriemer**
https://bugzilla.mozilla.org/show_bug.cgi?id=1138690

Load settings before loading `init`. Fixes the login reset issue currently on -dev.

### CODE REVIEW

**Comment by ngokevin** [comment]
Can we load it in init.js? I know we want to keep it super agnostic, but it's *marketplace*-core-modules and [traditionally we have expected a settings file to exist](https://github.com/mozilla/commonplace/blob/b9d1cfd5edb750151867aa4687c4662c385d2c90/dist/core/init.js#L9). That way we can encapsulate that logic in init.js and not have to do this for every app.

**Comment by mstriemer** [comment]
Closing in favour of https://github.com/mozilla/marketplace-gulp/pull/11 and https://github.com/mozilla/marketplace-core-modules/pull/29.

**Comment by ngokevin** [comment]
r+

**Comment by mstriemer** [comment]
I made some other changes to get `routes` loading early also and put them in https://github.com/mozilla/fireplace/pull/1054. Closing in favour of that.

**Pull request closed without merging**
