### PR TITLE
remove platform selector for mobile (bug 1205141)

### PR DESCRIPTION
**Pull request by ngokevin**

### CODE REVIEW

**Comment by spasovski** [comment]
Still missing for me on Desktop.

**Comment by ngokevin** [comment]
Accidentally added some last-minute changes that broke it, it should be back now.

**Comment by ngokevin** [comment]
[Sherlocked](http://sherlocked.dev.mozaws.net/builds/81837161) shows that it's added back now. It won't reflect the mobile changes since it's testing desktop browsers ATM.

**Comment by sherlockedci** [comment]
[ The Adventure of the Mazarin Build](http://sherlocked.dev.mozaws.net/builds/81837161)

**Comment by spasovski** [comment]
Looks good locally now r+

**Comment by ngokevin** [comment]
thanks

**Pull request merged**
