### PR TITLE
Fix openmobile ACL activity spinner (bug 1194464)

### PR DESCRIPTION
**Pull request by diox**
https://bugzilla.mozilla.org/show_bug.cgi?id=1194464

### CODE REVIEW

**Comment by chuckharmston** [comment]
Ah, darn it. I just finished flashing my phone to work on this bug.

**Comment by diox** [comment]
Ah, sorry, ddurst told me I should try to do it since you were stuck. Bonus: you can test my code on your device! I'm writing documentation right now.

**Comment by chuckharmston** [comment]
There's a weird edge case here we probably don't need to concern ourselves with, but should think about anyway: what happens if you're installing an ACL via App 1, and visit App 2's detail page?

**Comment by diox** [comment]
You're free to visit another app and we don't really care about it. The ACL install will proceed anyway, and you should not see a spinning button on other pages.

Docs: https://wiki.mozilla.org/Marketplace/OpenMobile

**Comment by chuckharmston** [comment]
These docs are excellent, thank you.

**Comment by chuckharmston** [comment]
I can't reproduce with this patch anymore, r+

**Pull request merged**
