### PR TITLE
nav polish

### PR DESCRIPTION
**Pull request by chuckharmston**
I'll keep a running set of commits and before/after screenshots here for reference.

### CODE REVIEW

**Comment by chuckharmston** [comment]
## Before

screen shot 2015-10-27 at 4 43 17 pm

## After

screen shot 2015-10-27 at 4 50 43 pm

**Comment by chuckharmston** [comment]
## Before



## After

**Comment by chuckharmston** [comment]
## Before

screen shot 2015-10-27 at 5 06 31 pm

screen shot 2015-10-27 at 5 06 21 pm

## After

screen shot 2015-10-27 at 5 10 19 pm

screen shot 2015-10-27 at 5 06 04 pm

**Comment by chuckharmston** [comment]
## Before





## After

**Comment by chuckharmston** [comment]
# Before



# After

**Comment by chuckharmston** [comment]
## Before

screen shot 2015-10-27 at 5 47 24 pm

screen shot 2015-10-27 at 5 47 29 pm

## After 

screen shot 2015-10-27 at 5 48 27 pm

screen shot 2015-10-27 at 5 48 38 pm

**Comment by chuckharmston** [comment]
## Before

screen shot 2015-10-27 at 5 56 04 pm

screen shot 2015-10-27 at 5 56 11 pm

## After

screen shot 2015-10-27 at 5 54 58 pm

screen shot 2015-10-27 at 5 57 48 pm

**Comment by ngokevin** [comment]
r+

**Comment by chuckharmston** [comment]
## Before

screen shot 2015-10-27 at 6 14 00 pm

screen shot 2015-10-27 at 6 13 56 pm

screen shot 2015-10-27 at 6 10 49 pm

screen shot 2015-10-27 at 6 13 47 pm


## After

screen shot 2015-10-27 at 6 10 28 pm

screen shot 2015-10-27 at 6 10 34 pm

screen shot 2015-10-27 at 6 10 43 pm

screen shot 2015-10-27 at 6 10 49 pm

**Pull request merged**
