### PR TITLE
content filter (bug 1161860)

### PR DESCRIPTION
**Pull request by ngokevin**
- reuse ```<mkt-select>```
- waffled under ```settings.meowEnabled```

screen shot 2015-05-14 at 1 43 11 pm
screen shot 2015-05-14 at 1 43 08 pm

### CODE REVIEW

**Comment by ngokevin** [comment]
@pwalm visual guidance on the custom select? i know this one i whipped up probably won't fly

**Comment by pwalm** [comment]
Should just be a standard drop down:
screen shot 2015-05-14 at 1 21 53 pm

**Comment by ngokevin** [comment]
That causes trouble since "SHOW" in other languages will often not fit.

**Comment by pwalm** [comment]
Let's put it all in the drop down: "Show all content", "Show websites", "Show apps"

**Comment by mstriemer** [comment]
Should `content_filter.apiArgs` get hooked into the router's processors?

**Comment by ngokevin** [comment]
it's already all in the dropdown :P

**Comment by ngokevin** [comment]
Not yet, unless the API is ready for that.

**Comment by mstriemer** [comment]
I don't think it is.

**Comment by ngokevin** [comment]
Tweaked the select to look more like the mock.

**Comment by mstriemer** [comment]
What's the advantage of a `<mkt-select>` over a `<select>` here?

**Comment by ngokevin** [comment]
mkt-select is more stylizable. it's very hard to style a native select

**Comment by mstriemer** [comment]
Cool, r+

**Comment by ngokevin** [comment]
TODO l8r: hook up in api args processor. UA. thanks y'all

**Pull request merged**
