### PR TITLE
show stats button to the *right* people (bug 1127860)

### PR DESCRIPTION
**Pull request by spasovski**

### CODE REVIEW

**Comment by ngokevin** [comment]
maybe a quick check that it is hidden to not logged in user

r+wc nice

**Comment by spasovski** [comment]
Not sure how I'd check the public stats flag first for that test

**Comment by ngokevin** [comment]
It's not visible by default right? Can we just check assertDoesntExist?

**Comment by spasovski** [comment]
Yea wasn't sure how the result is coming back from the API...true though if it's not set it'd be false

**Pull request merged**
