### PR TITLE
 Bug 1080289 - Page title of "My Account" page is "Account Settings" 

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
changed string "Account Settings" to "My Account"

### CODE REVIEW

**Comment by clouserw** [comment]
Please squash these commits into one

**Comment by atiqueahmedziad** [comment]
Done. updated . Please review now :)

**Comment by ngokevin** [comment]
can you make it just "Settings" now? the nav has since changed to read ```Settings```.

**Comment by atiqueahmedziad** [comment]
Did you mean to change the string "My Account" with only "Settings"?

**Comment by ngokevin** [comment]
Instead of changing it to ```My Account```, you can change it to just ```Settings```.

**Comment by atiqueahmedziad** [comment]
@ngokevin  Please check now, :)

**Pull request closed without merging**
