### PR TITLE
Fix hub/spoke header for Homepage & My Apps

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
### Before
screen shot 2015-12-05 at 06 00 44
### After
screen shot 2015-12-05 at 06 00 48

### Before
screen shot 2015-12-05 at 06 01 06
### After
screen shot 2015-12-05 at 06 01 13

### CODE REVIEW

**Comment by ngokevin** [comment]
how does that look in other languages where the string can get long?

**Comment by atiqueahmedziad** [comment]
I tried a couple of language with Marketplace header- "Firefox Marketplace". But it seems that the string in other languages also not long enough to `overflow`
I tried with Arabic, Bengali, Urdu, Chinese, French, 
screen shot 2015-12-06 at 00 15 46
screen shot 2015-12-06 at 00 15 03
screen shot 2015-12-06 at 00 15 30
screen shot 2015-12-06 at 00 17 48

**Comment by atiqueahmedziad** [comment]
We can increase the title width upto `225px;` if so, we can input upto 24 characters. 
screen shot 2015-12-06 at 00 57 59

**Comment by ddurst** [comment]
@atiqueahmedziad -- I would say change it to "FirefoxOS Marketplace" and leave it at 215px (assuming it fits).

**Comment by atiqueahmedziad** [comment]
closing it for #1614

**Pull request closed without merging**
