### PR TITLE
use body type for author in app tiles

### PR DESCRIPTION
**Pull request by ngokevin**
@pwalm r? The current author type looks a bit outdated compared to the rest of the site

screen shot 2015-02-13 at 1 07 50 pm

### CODE REVIEW

**Comment by pwalm** [comment]
Sorry, which is "author type"?

**Comment by ngokevin** [comment]
typography for the author name in the app tiles

**Comment by pwalm** [comment]
Looks light, it should be regular.

**Comment by ngokevin** [comment]
Okay, just tweaked the color instead

**Pull request closed without merging**
