### PR TITLE
Add horizontal separator to website detail under button (bug 1175675)

### PR DESCRIPTION
**Pull request by mstriemer**
https://bugzilla.mozilla.org/show_bug.cgi?id=1175675

### CODE REVIEW

**Comment by sherlockedci** [comment]
[ The Adventure of the Engineer's Build](http://sherlocked.dev.mozaws.net/builds/69483035)

**Comment by spasovski** [comment]
He's on PTO but it seems like an r+

**Comment by mstriemer** [comment]
Thanks

**Pull request merged**
