### PR TITLE
Bug 1058508 - Line-height is off for reviews stars/text on detail page

### PR DESCRIPTION
**Pull request by tsl143**

### CODE REVIEW

**Comment by spasovski** [comment]
Have you tested how this looks on FxOS mobile? I believe it was added to fix a misalignment in the mobile browser.

**Comment by tsl143** [comment]
Tested on flame

**Comment by ngokevin** [comment]
@tsl143 could you do us a favor and attach screenshots of what it now looks like, on both desktop and firefoxOS? thanks!

**Comment by tsl143** [comment]
screen shot 2015-08-05 at 11 22 38
screen shot 2015-08-05 at 11 23 02

**Comment by ngokevin** [comment]
looks good, thanks!

**Pull request merged**
