### PR TITLE
Use Math.pow instead of bitwise XOR when trying to do exponents.

### PR DESCRIPTION
**Pull request by chuckharmston**
r?

### CODE REVIEW

**Comment by diox** [comment]
Would be nice to have tests, they would have detected the issue with ^.

r+wc

**Comment by diox** [comment]
(funny enough for apps we cheat and the fireplace APIs format the size in python before returning it)

**Comment by sherlockedci** [comment]
[ The Adventure of the Resident Build](http://sherlocked.dev.mozaws.net/builds/81040350)

**Comment by diox** [comment]
r+

**Comment by sherlockedci** [comment]
[ The Adventure of the Mazarin Build](http://sherlocked.dev.mozaws.net/builds/82589829)

**Comment by sherlockedci** [comment]
[ The Adventure of the Thor Build](http://sherlocked.dev.mozaws.net/builds/82589973)

**Comment by chuckharmston** [comment]
Thanks!

**Pull request merged**
