### PR TITLE
update OS X banner wording (bug 1135156)

### PR DESCRIPTION
**Pull request by ngokevin**
stamped by liz + cvan

### CODE REVIEW

**Comment by spasovski** [comment]
I like this better personally but I wonder if we should run it by Liz Hunt.

**Comment by ngokevin** [comment]
She saw it in irc, it's pending

**Comment by ddurst** [comment]
lol

**Comment by ezoehunt** [comment]
lol cubed

**Comment by cvan** [comment]
proud of you for this one

**Comment by chuckharmston** [comment]
grammar-police

**Pull request merged**
