### PR TITLE
Use JS to open websites in a new window (bug 1192991).

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @ngokevin 

Using `<a target="_blank">` doesn't work for some reason, gotta force it through with `window.open`.

### CODE REVIEW

**Comment by ngokevin** [comment]
It's ```target="_blank"``` no?

**Comment by chuckharmston** [comment]
Yeah, that's what I meant. Still didn't work.

**Comment by chuckharmston** [comment]
Worked from the site, not from the package, I should say.

**Comment by ngokevin** [comment]
Okay, because it's within an iframe. Might try target=_self, but r+

**Comment by chuckharmston** [comment]
I thought about that, but `target=_self` wouldn't be the desired behavior when in the browser. Edge case, but I guess an important one. Thanks!

**Pull request merged**
