### PR TITLE
Bug 1189337 | Remove footer + Sign Out button on settings page

### PR DESCRIPTION
**Pull request by shahbaz17**

### CODE REVIEW

**Comment by gurumukhi** [comment]
Hi @shahbaz17 I thing you can keep it open, @tsl143 mentioned that this PR failed to pass travis but that should not matter for it to be merged if the code changes are correct. 

@ddurst am I correct above?

**Comment by gurumukhi** [comment]
checked https://github.com/mozilla/fireplace/pull/1414 now, you will have to pas the checks.

**Comment by gurumukhi** [comment]
again checks failed :(
@ddurst can you suggest @shahbaz17 whats wrong here and how to get the checks passed?

**Comment by shahbaz17** [comment]
https://github.com/mozilla/fireplace/pull/1428 opening this..

**Comment by gurumukhi** [comment]
Are you going to send new Pull Request?

**Comment by shahbaz17** [comment]
#1428 this have failed :( what to do next?

**Comment by spasovski** [comment]
@shahbaz17 there are 2 tests in `tests/ui/settings.js` that log the user out by clicking the footer "sign out" link. These tests should be changed/removed for the PR to pass. Please feel free to ask in IRC if you would like some help with this.

**Comment by ngokevin** [comment]
This is close. Just remove all occurrences of logout from https://github.com/mozilla/fireplace/blob/master/tests/ui/settings.js

**Comment by tsl143** [comment]
@shahbaz17 try the suggestion please

**Comment by ngokevin** [comment]
dupe PR as opened for this

**Pull request closed without merging**
