### PR TITLE
Use market_button for add-on button status (bug 1213330).

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @ngokevin 

screen shot 2015-10-23 at 1 30 34 pm

### CODE REVIEW

**Comment by ngokevin** [comment]
looking

**Comment by sherlockedci** [comment]
[ The Adventure of the Abbey Build](http://sherlocked.dev.mozaws.net/builds/87102752)

**Comment by ngokevin** [comment]
Kept spinning for a bit after it finished installing.

screen shot 2015-10-23 at 12 48 23 pm

**Comment by ngokevin** [comment]
Clicking on the install button on listing page often leads me to detail page

**Comment by chuckharmston** [comment]
Be more precise with your clicking.

**Comment by ngokevin** [comment]
When refreshing the page, the add-on loses its installed state

**Comment by sherlockedci** [comment]
[ The Adventure of the Black Build](http://sherlocked.dev.mozaws.net/builds/87109260)

**Comment by chuckharmston** [comment]
I think you do need to be on 2.5 for that. WFM.

**Comment by ngokevin** [comment]
r+

**Comment by sherlockedci** [comment]
[ The Adventure of the Reigate Build](http://sherlocked.dev.mozaws.net/builds/87112873)

**Pull request merged**
