### PR TITLE
always insert banners before header (1515)

### PR DESCRIPTION
**Pull request by spasovski**
This won't change anything for the desktop header since it's absolutely positioned. To test this locally try http://pastebin.com/HC0Y5XGA

### CODE REVIEW

**Comment by ngokevin** [comment]
bug #?

**Comment by spasovski** [comment]
None that I know of, was requested by DDurst.

**Comment by chuckharmston** [comment]
What about the mac banner?

**Comment by spasovski** [comment]
Bug 1219083 is open. This isn't meant to address that. @ddurst can weigh in.

**Comment by ddurst** [comment]
We hadn't filed one yet, this was noticed by QA -- that the banner wasn't shown because it was behind the nav. But, yes, it's similar to but different from 1219083.

**Comment by chuckharmston** [comment]
Let's get a better commit message then, it sort of implies that you want to do up all the banners in that way.

**Comment by chuckharmston** [comment]
r+wc

**Comment by chuckharmston** [comment]
Merging to unblock late customization.

**Pull request merged**
