### PR TITLE
re-add route_api_args for region, carrier (bug 1263613)

### PR DESCRIPTION
**Pull request by spasovski**
Good catch @ddurst. Sorry about the lateness.

This worked well locally and the region got added to each XHR but I encourage further testing.

### CODE REVIEW

**Comment by ddurst** [comment]
I would say we should add back the changes to tests/unit/rewriters.js, but it looks like none of those tests really required those anyway...

**Comment by diox** [comment]
https://github.com/mozilla/fireplace/commit/08c19f7c8179d67776b93851403f82396046badf also removed some feature profile code that should probably also be kept if we want feature requirements to work.

**Comment by ddurst** [comment]
@diox Which parts? If we can add them back in today, I can get them pushed today.

**Comment by diox** [comment]
Everything related to feature profile in that commit :) It's a bit intertwined.

**Comment by ddurst** [comment]
oy

**Comment by spasovski** [comment]
If we want to keep feature profiles it's better to revert the original and simply not inject the platform selector template. We can ignore this PR.

**Pull request closed without merging**
