### PR TITLE
fix loading spinner footer overlap (bug 1121215)

### PR DESCRIPTION
**Pull request by spasovski**

### CODE REVIEW

**Comment by ngokevin** [comment]
aren't we spinning the spinner within the button?

**Comment by spasovski** [comment]
Not currently. @pwalm thoughts?

**Comment by ngokevin** [comment]
as in aren't we supposed to implement that?*

**Comment by spasovski** [comment]
I was never told to explicitly make the little icon next to the Load More do an animated spin, it's doable just wanted to confirm with Phil.

**Pull request closed without merging**
